Fix macOS version on available attributes
Otherwise, it causes build error with Xcode 8.2:

```log
/Users/cosmo/GitHub/sushibar/sushibar/AppDelegate.swift:23:19: error:
'NSTouchBar' is only available on OS X 10.12.2 or newer
    var touchBar: NSTouchBar?
                      ^
```